### ISSUE TITLE
Have an issue of "Cannot connect to the Docker daemon at unix"

### ISSUE THREAD

**Issue by SFARL** [nyu-devops/lab-docker#11]
Hi Prof,
I met an issue like this when I run "docker run hello-world". 
<img width="1013" alt="截屏2023-02-01 下午10 13 04" src="https://user-images.githubusercontent.com/47218220/216222697-5bc0a9d2-9e10-4da1-863e-e1e1c30ee6be.png">

vscode@nyu:/app$ docker run hello-world
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.

**Comment by rofrano** [comment]
Hi @SFARL I would remove the container and delete the image and have VS Code rebuild it. Something may have gone wrong during the image build.

Exit VS Code. Then from a terminal use:

```bash
docker rm lab-docker
docker rmi {image_id}
```

Where `{image_id}` is the id of the image returned from `docker image ls`. 

Then restart VS Code and have it rebuild everything.

```bash
code .
```

See if that helps.

**Comment by SFARL** [comment]
It works after updating VScode to the latest version.
